In [1]:
import pandas as pd
import numpy as np

print("Setup working")

Setup working

In [2]:
import requests

API_KEY = "YOUR_NEW_API_KEY"

url = f"https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}"

response = requests.get(url)
data = response.json()

data.keys()

dict_keys(['status_code', 'status_message', 'success'])

In [3]:
import requests

API_KEY = "9af4f73fa1d57fda800a2ccddd43fed7"

url = f"https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}"

response = requests.get(url)
data = response.json()

data.keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [5]:
movies = data['results']

In [6]:
movie_list = []
for movie in movies:
    movie_list.append({
        "title": movie["title"],
        "rating": movie["vote_average"],
        "popularity": movie["popularity"],
        "overview": movie["overview"],
        "release_date": movie["release_date"]
    })

In [7]:
import pandas as pd

df = pd.DataFrame(movie_list)
df.head()

,title,rating,popularity,overview,release_date
0,The Super Mario Galaxy Movie,6.700,471.5305,Having thwarted Bowser's previous plot to marr...,2026-04-01
1,Apex,6.432,395.3686,A grieving woman pushing her limits on a solo ...,2026-04-24
2,Swapped,7.975,380.4680,"A small woodland creature and a majestic bird,...",2026-05-01
3,Malena,7.429,318.4266,12-year-old Renato experiences three significa...,2000-10-27
4,Send Help,6.989,247.3239,Two colleagues become stranded on a deserted i...,2026-01-22

In [8]:
df['overview'] = df['overview'].fillna('')

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(df['overview'])

In [10]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(tfidf_matrix)

In [11]:
def recommend(movie_title):
    index = df[df['title'] == movie_title].index[0]
    
    distances = similarity[index]
    
    movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]
    
    for i in movie_list:
        print(df.iloc[i[0]].title)

In [12]:
recommend("Malena")

Shelter
Tayuan 2
The Super Mario Galaxy Movie
Michael
Avatar: Fire and Ash

In [1]:
print("Jupyter working")

Jupyter working

In [2]:
df.head()

NameError: name 'df' is not defined

In [3]:
movie_list = []

for movie in data['results']:
    movie_list.append({
        "title": movie["title"],
        "rating": movie["vote_average"],
        "popularity": movie["popularity"],
        "overview": movie["overview"],
        "release_date": movie["release_date"]
    })

NameError: name 'data' is not defined

In [4]:
import pandas as pd

df = pd.DataFrame(movie_list)
df.head()

Empty DataFrame
Columns: []
Index: []

In [5]:
df.to_csv("../data/movies.csv", index=False)

In [6]:
import os
os.listdir("../data")

['movies.csv']

In [1]:
print("kernel working")

kernel working

In [1]:
import requests

API_KEY = "your_api_key_here"
url = f"https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}"

response = requests.get(url)
data = response.json()

In [2]:
import requests
import pandas as pd

API_KEY = "9af4f73fa1d57fda800a2ccddd43fed7"

url = f"https://api.themoviedb.org/3/movie/popular?api_key={API_KEY}"

response = requests.get(url)

data = response.json()

movies = data['results']

movie_list = []

for movie in movies:

    genre_ids = movie.get('genre_ids', [])

    movie_list.append({
        "movie_id": movie["id"],
        "title": movie["title"],
        "overview": movie["overview"],
        "rating": movie["vote_average"],
        "popularity": movie["popularity"],
        "release_date": movie["release_date"],
        "poster_path": movie["poster_path"],
        "genre_ids": genre_ids
    })

df = pd.DataFrame(movie_list)

df.head()

,movie_id,title,overview,rating,popularity,release_date,poster_path,genre_ids
0,1226863,The Super Mario Galaxy Movie,Having thwarted Bowser's previous plot to marr...,6.700,455.6196,2026-04-01,/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg,"[10751, 35, 12, 14, 16]"
1,1007757,Swapped,"A small woodland creature and a majestic bird,...",8.882,475.4302,2026-05-01,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,"[12, 16, 10751, 14]"
2,1318447,Apex,A grieving woman pushing her limits on a solo ...,6.554,356.4896,2026-04-24,/eTp7gSPkSF3Aw79mNx1NkBP1PZT.jpg,"[28, 53]"
3,10867,Malena,12-year-old Renato experiences three significa...,7.431,197.6598,2000-10-27,/3OyQTl0IGkbnjDxd3MhztfPE34g.jpg,[18]
4,1198994,Send Help,Two colleagues become stranded on a deserted i...,7.022,271.4875,2026-01-22,/mjkS2iAgWj3ik1DTjvI15nHZ7yl.jpg,"[27, 53, 35]"

In [3]:
df.to_csv("../data/movies_v2.csv", index=False)

In [4]:
import os
os.listdir("../data")

['movies.csv', 'movies_v2.csv']

In [5]:
genre_dict = {
    28: "Action",
    12: "Adventure",
    16: "Animation",
    35: "Comedy",
    80: "Crime",
    99: "Documentary",
    18: "Drama",
    10751: "Family",
    14: "Fantasy",
    36: "History",
    27: "Horror",
    10402: "Music",
    9648: "Mystery",
    10749: "Romance",
    878: "Science Fiction",
    10770: "TV Movie",
    53: "Thriller",
    10752: "War",
    37: "Western"
}

In [6]:
def convert_genres(genre_ids):

    genre_names = []

    for genre_id in genre_ids:

        if genre_id in genre_dict:
            genre_names.append(genre_dict[genre_id])

    return " ".join(genre_names)

df['genres'] = df['genre_ids'].apply(convert_genres)

df[['title', 'genres']].head()

                          title                                     genres
0  The Super Mario Galaxy Movie  Family Comedy Adventure Fantasy Animation
1                       Swapped         Adventure Animation Family Fantasy
2                          Apex                            Action Thriller
3                        Malena                                      Drama
4                     Send Help                     Horror Thriller Comedy

In [7]:
df['combined_features'] = (
    df['title'].fillna('') + ' ' +
    df['overview'].fillna('') + ' ' +
    df['genres'].fillna('')
)

df[['title', 'combined_features']].head()

,title,combined_features
0,The Super Mario Galaxy Movie,The Super Mario Galaxy Movie Having thwarted B...
1,Swapped,Swapped A small woodland creature and a majest...
2,Apex,Apex A grieving woman pushing her limits on a ...
3,Malena,Malena 12-year-old Renato experiences three si...
4,Send Help,Send Help Two colleagues become stranded on a ...

In [8]:
df.to_csv("../data/movies_v2.csv", index=False)

In [9]:
df.columns

Index(['movie_id', 'title', 'overview', 'rating', 'popularity', 'release_date',
       'poster_path', 'genre_ids', 'genres', 'combined_features'],
      dtype='str')

In [10]:
df.columns

Index(['movie_id', 'title', 'overview', 'rating', 'popularity', 'release_date',
       'poster_path', 'genre_ids', 'genres', 'combined_features'],
      dtype='str')

In [11]:
df['imdb_link'] = ""

In [12]:
df.loc[df['title'] == 'Inception', 'imdb_link'] = 'https://www.imdb.com/title/tt1375666/'
df.loc[df['title'] == 'Interstellar', 'imdb_link'] = 'https://www.imdb.com/title/tt0816692/'
df.loc[df['title'] == 'The Matrix', 'imdb_link'] = 'https://www.imdb.com/title/tt0133093/'

In [13]:
df.to_csv('../data/movies_v2.csv', index=False)

In [14]:
df['imdb_link'].head(10)

0
1
2
3
4
5
6
7
8
9
Name: imdb_link, dtype: str

In [15]:
df['imdb_link'] = "https://www.themoviedb.org/movie/" + df['movie_id'].astype(str)

In [16]:
df.to_csv('../data/movies_v2.csv', index=False)